// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace React_Northwind.Models
{
    public partial class Course
    {
        public string Cid { get; set; }
        public string Cname { get; set; }
        public string Tid { get; set; }
    }
}