// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace React_Northwind.Models
{
    public partial class Student
    {
        public string Sid { get; set; }
        public string Sname { get; set; }
        public DateTime? Sage { get; set; }
        public string Ssex { get; set; }
    }
}