// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace React_Northwind.Models
{
    public partial class ViewPSum
    {
        public int Product { get; set; }
        public float? PSum { get; set; }
    }
}